### ISSUE TITLE
Plantilla no encontrada

### ISSUE THREAD

**Issue by Karina-27** [biogeografia-202401/practicas#1]
La plantilla del manuscrito para Microsoft Word no se encuentra disponible. Esta es la ruta del archivo: [practicas](https://github.com/biogeografia-202401/practicas/tree/main)/[data](https://github.com/biogeografia-202401/practicas/tree/main/data)
/plantilla-manuscrito.dotx

**Comment by geofis** [comment]
Oops, añadida la plantilla en el último commit.
